### ISSUE TITLE
Keep track of Microcks instance using something like `context file`

### ISSUE THREAD

**Issue by Harsh4902** [microcks/microcks-cli#136]
### Reason/Context

- We are going to add support for `start` and `stop` command for our CLI tool, which will help to start and stop a microcks container.
- For this feature, we have to keep track of existing microcks container so that en execution of `start` or `stop` command can be efficient.

### Description

- Execution of `start` or `stop` command will may lead us toward some failure.
- To prevent this, we have to keep track of existing microcks container using something like `context file`.

**Comment by lbroudoux** [comment]
Having a `~/.microcks/config` sounds nice and it will mimic `~/.kube/config` stuff.

It could also track the name of created container during a `microcks start` to later know which container to health check with `microcks status` or to stop with `microcks stop`: 💯 

I can also imagine as you suggest having the default image used for creating local instances with microcks start 👍

**Comment by lbroudoux** [comment]
This is a part of #97

**Comment by lbroudoux** [comment]
A context could be something like:

```yaml
microckses:
  - name: domain1
    server: https://domain1-microcks.acme.org
  - name: domain2
    server: https://domain2-microcks.acme.org
contexts:
  - microcks: domain1
    user: admin
    refreshToken: sha256~gbBF....
  - microcks: domain2
    user: laurent
    refreshToken: sha256~gbBF....
current-context: ""
```

(just a proposition to refine)à
