### ISSUE TITLE
connection refused, keycloak config issue for grpc proto import

### ISSUE THREAD

**Issue by GomesNayagam** [microcks/microcks-cli#144]
Hi,

I am using the cli tool to setup and run in side docker using docker compose, but i am getting error connection refused. in import cli  container but it is looks imported all proto services andi i am able to invoke with sample too. 

But the dispatch rule is not applied (metadata).

can you help me on this.

```yaml
services:
  grpc-mocks:
    image: quay.io/microcks/microcks-uber:1.11.0
    ports:
      - '9081:8080' # Admin UI http://localhost:9081/
      - '9201:9090' # gRPC port

  grpc-mocks-importer:
    depends_on:
      - grpc-mocks
    restart: on-failure
    image: quay.io/microcks/microcks-cli:latest
    volumes:
      - C:\gomes\microcks-pnp\policy_service_v1.proto:/resources/protos/policy_service_v1.proto
      - C:\gomes\microcks-pnp\policy_service_example.yaml:/resources/api-examples/policy_service_example.yaml
      - C:\gomes\microcks-pnp\policy_service_metadata.yaml:/resources/api-examples/policy_service_metadata.yaml
    entrypoint: >
      bash -c "microcks-cli import '/resources/protos/policy_service_v1.proto:true,/resources/api-examples/policy_service_example.yaml:false,/resources/api-examples/policy_service_metadata.yaml:false' --microcksURL=http://grpc-mocks:8080/api  --keycloakClientId=microcks-serviceaccount --keycloakClientSecret=ab54d329-e435-41ae-a900-ec6b3fe15c54 --insecure"
```

Error:

2025-04-16 19:37:35 Got error when invoking Microcks client retrieving config: Get "http://grpc-mocks:8080/api/keycloak/config": dial tcp 172.18.0.2:8080: connect: connection refused2025-04-17T02:37:36.378883297Z Got error when invoking Microcks client retrieving config: Get "http://grpc-mocks:8080/api/keycloak/config": dial tcp 172.18.0.2:8080: connect: connection refused2025-04-17T02:37:37.054125374Z Got error when invoking Microcks client retrieving config: Get "http://grpc-mocks:8080/api/keycloak/config": dial tcp 172.18.0.2:8080: connect: connection refused2025-04-17T02:37:37.757184752Z Got error when invoking Microcks client retrieving config: Get "http://grpc-mocks:8080/api/keycloak/config": dial tcp 172.18.0.2:8080: connect: connection refused2025-04-17T02:37:38.797290231Z Got error when invoking Microcks client retrieving config: Get "http://grpc-mocks:8080/api/keycloak/config": dial tcp 172.18.0.2:8080: connect: connection refused2025-04-17T02:37:40.646236318Z Got error when invoking Microcks client retrieving config: Get "http://grpc-mocks:8080/api/keycloak/config": dial tcp 172.18.0.2:8080: connect: connection refused2025-04-17T02:37:44.452470285Z Microcks has discovered 'org.pnp.policy.v1.PolicyService:v1'
2025-04-16 19:37:44 Microcks has discovered 'org.pnp.policy.v1.PolicyService:v1'
