### ISSUE TITLE
[Feature request] Support for disabled keycloak case

### ISSUE THREAD

**Issue by SPONGE-JL** [microcks/microcks-cli#27]
### Reason/Context

To enhance using local development cycle, [as microcks discussion on \#843](https://github.com/orgs/microcks/discussions/873#discussioncomment-6381192), the microcks container run without keycloak with this option: `KEYCLOAK_ENABLED=false`

To import local file in repository where the compose file exist, I used `microcks-cli`'s `import` command using docker-compose:

```yaml
importer:
  image: quay.io/microcks/microcks-cli:latest
  volumes:
    - "./openapi:/specs"
  entrypoint:
    - microcks-cli
    - import
    - '/specs/index.html:true'
    - --insecure
    - --microcksURL=http://app:8080/api
```

I try to run the `importer` service:

```bash
docker compose up importer
```

Then the container has response like this:

```plantext
--keycloakClientId flag is mandatory. Check Usage.
# exited with code 1
```

Would the teams handle this case?

### Description

Used container version: `latest` -> `0.5.2`([902cca76a48d](https://quay.io/repository/microcks/microcks-cli/manifest/sha256:902cca76a48d1c0604f7cf506badbd6f1701e115b417bf798e78cb0532e7c647))

### Implementation ideas

Maybe the error message has been printed by [/cmd/import.go#L57-L64C3](https://github.com/microcks/microcks-cli/blob/master/cmd/import.go#L57-L64C3).

**Comment by SPONGE-JL** [comment]
Currently, this request maybe parked TODOs.

I handled this case using [`curl` with advice](https://github.com/orgs/microcks/discussions/873#discussioncomment-6384020).

```bash
# call in host where microcks container(`:8080`) has run in compose network
curl -F "file=@./openapi/index.yaml" \
  http://localhost:8080/api/artifact/upload
```

**Comment by lbroudoux** [comment]
Hey there! It appears that this was already addressed with #23. Could you check again please?

**Comment by lbroudoux** [comment]
It is actually working but you still need to set the `--keycloakClientId` and `--keycloakClientSecret` flags with dummy values.

The following command works on my side: 
```sh
$ microcks-cli test 'API Pastries:0.0.1' http://localhost:3002 OPEN_API_SCHEMA --microcksURL=http://localhost:8080/api --keycloakClientId=foo --keycloakClientSecret=bar`
```

**Comment by SPONGE-JL** [comment]
Hi @lbroudoux, good to see you

In my case, I try to `import` using the `microcks-cli` as I wrote above, but maybe same with `test` command as you told.

Here is my footprint:

```yaml
# in docker-compose.yaml
services:
  importer:
    image: quay.io/microcks/microcks-cli:latest
    volumes:
      - "./spes/openapi:/specs"
    entrypoint:
      - microcks-cli
      - import
      - '/specs/index.html:true'
      - --microcksURL=http://stub:8080/api --insecure
      # Disable Authentication in local
      - --keycloakClientId=foo # dummyForAnonymousId
      - --keycloakClientSecret=bar # dummyForAnonymousSecret

  app:
    # hide other props
    image: quay.io/microcks/microcks:1.7.1
    environment:
      # hide other configs
      - KEYCLOAK_ENABLED=false
```

I run below command to import OpenAPI.yaml to Microks

```bash
docker compose up importer
```

Then below message has been appeared:

```plain text
Attaching to importer
importer  | panic: interface conversion: interface {} is nil, not bool
importer  | 
importer  |  goroutine 1 [running]:
importer  |  github.com/microcks/microcks-cli/pkg/connectors.(*microcksClient).GetKeycloakURL(0xc0000ce120)
importer  |      /Users/lbroudoux/Development/temp/microcks-cli/pkg/connectors/microcks_client.go:110 +0x515
importer  |  github.com/microcks/microcks-cli/cmd.(*importComamnd).Execute(0x656520?)
importer  |     /Users/lbroudoux/Development/temp/microcks-cli/cmd/import.go:80 +0x5d3
importer  | main.main()
importer  |     /Users/lbroudoux/Development/temp/microcks-cli/main.go:31 +0x103
importer  | 
importer exited with code 2
```

So currently, I cannot try the `test` command what you told.
Sorry to say that, would you check upper context?

**Comment by lbroudoux** [comment]
Sure! I'm gonna check this.

**Comment by lbroudoux** [comment]
The error `github.com/microcks/microcks-cli/pkg/connectors.(*microcksClient).GetKeycloakURL(0xc0000ce120)` is relative to connecting to Microcks to retrieve the Keycloak URL. This is a common step that is done before trying the authentication (that should not happen here because `KEYCLOAK_ENABLED` is `false`).

I tried with your config and I encountered a first problem with `- --microcksURL=http://stub:8080/api --insecure` as I got this following error from `importer` container: 

```
Got error when invoking Microcks client retrieving config: Get "http://stub:8080/api%20--insecure/keycloak/config": dial tcp: lookup stub on 127.0.0.11:53: no such host
```

So I changed things a bit and got following `docker-compose.yml` file:

```yaml
services:
  importer:
    image: quay.io/microcks/microcks-cli:latest
    volumes:
      - "./samples:/samples"
    entrypoint:
      - microcks-cli
      - import
      - '/samples/weather-forecast-openapi.yml:true'
      - --microcksURL=http://stub:8080/api 
      - --insecure
      - --keycloakClientId=foo
      - --keycloakClientSecret=bar

  stub:
    # hide other props
    image: quay.io/microcks/microcks:1.7.1
    environment:
      # hide other configs
      - KEYCLOAK_ENABLED=false
```

As I don't have your spec at hand, I put this into the `microcks-cli` root folder and try to reuse our `weather-forecast-openapi.yml` sample. Run again your command and got following result:

```sh
$ docker-compose up importer
[+] Running 2/2
 ⠿ Network microcks-cli_default       Created     0.0s
 ⠿ Container microcks-cli-importer-1  Created     0.1s
Attaching to microcks-cli-importer-1
microcks-cli-importer-1 exited with code 1
```

The result is different here (code 1 instead of 2) but I see 2 problems here with this file:
* First Microcks `1.7.1` absolutely need a MongoDB database (or maybe you remove everything from your docker-compose file)
* Then, nothing prevents your `importer` to run before Microcks is actually ready to receive requests. Actually, that's the case as I can see `Got error when invoking Microcks client retrieving config: Get "http://stub:8080/api/keycloak/config": dial tcp: lookup stub on 127.0.0.11:53: no such host` in the container logs.

To solve the first problem you may actually add everything related to Mongo that is missing into your docker-compose OR your can use our new `quay.io/microcks/microcks-uber` docker image 😉  This is a work in progress but it's already working and allows you to remove the mongo dependency (see https://github.com/microcks/microcks/tree/1.8.x/distro/uber#readme).

To solve the second problem, you'll need to put some dependency to order the startup of containers but also a retry policy as `stub` container may be started but not yet ready to receive import commands. Thus, I have modified your `docker-compose.yml` file like this:

```yaml
services:
  importer:
    depends_on:
      - stub
    restart: on-failure
    image: quay.io/microcks/microcks-cli:latest
    volumes:
      - "./samples:/samples"
    entrypoint:
      - microcks-cli
      - import
      - '/samples/weather-forecast-openapi.yml:true'
      - --microcksURL=http://stub:8080/api
      - --insecure
      - --keycloakClientId=foo
      - --keycloakClientSecret=bar

  stub:
    # no need for other props
    image: quay.io/microcks/microcks-uber:nightly
    ports:
      - "8080:8080"
```

and now everything is running fine:

```sh
$ docker compose up importer
[+] Running 3/2
 ⠿ Network microcks-cli_default       Created   0.0s
 ⠿ Container microcks-cli-stub-1      Created   0.0s
 ⠿ Container microcks-cli-importer-1  Created   0.0s
Attaching to microcks-cli-importer-1
microcks-cli-importer-1 exited with code 1
microcks-cli-importer-1 exited with code 1
microcks-cli-importer-1 exited with code 1
microcks-cli-importer-1 exited with code 1
microcks-cli-importer-1  | Microcks has discovered 'WeatherForecast API:1.1.0'
microcks-cli-importer-1 exited with code 0
```

You can even access `http://localhost:8080` in your browser after the import and check that your spec has been correctly imported.

Hope it helps,
